package compiler

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strings"
	"text/template"

	"github.com/jsell-rh/trusted-software-foundry/foundry/spec"
)

// --------------------------------------------------------------------------
// Multi-service codegen — generates main_<service>.go + docker-compose.yaml
// --------------------------------------------------------------------------

// toPascalCase converts a kebab-case name to PascalCase.
// "api-server" → "ApiServer", "worker" → "Worker"
func toPascalCase(s string) string {
	parts := strings.Split(s, "-")
	var sb strings.Builder
	for _, p := range parts {
		if len(p) > 0 {
			sb.WriteString(strings.ToUpper(p[:1]) + p[1:])
		}
	}
	return sb.String()
}

// toSnakeCase converts a kebab-case name to snake_case for file names.
// "api-server" → "api_server"
func toSnakeCase(s string) string {
	return strings.ReplaceAll(s, "-", "_")
}

var serviceMainTemplate = template.Must(template.New("svcmain").Funcs(template.FuncMap{
	"cleanAlias": func(name string) string {
		return strings.ReplaceAll(name, "-", "")
	},
	"pascal": toPascalCase,
}).Parse(`// Code generated by forge compile. DO NOT EDIT.
// Service: {{ .Service.Name }} (role: {{ .Service.Role }})
// Spec: {{ .IR.Metadata.Name }} v{{ .IR.Metadata.Version }}
package main

import (
	"context"
	"fmt"
	"os"
	"os/signal"
	"syscall"

	"github.com/jsell-rh/trusted-software-foundry/foundry/spec"
{{ range .Components }}	{{ cleanAlias .Name }} "{{ .Module }}"
{{ end }})

func main{{ pascal .Service.Name }}() {
	resources := []spec.ResourceDefinition{}
	app := spec.NewApplication(resources)
{{ range .Components }}	app.AddComponent({{ cleanAlias .Name }}.New())
{{ end }}
	{{ .ConfigsCode }}
	if err := app.Configure(configs); err != nil {
		fmt.Fprintf(os.Stderr, "configure: %v\n", err)
		os.Exit(1)
	}
	if err := app.Register(); err != nil {
		fmt.Fprintf(os.Stderr, "register: %v\n", err)
		os.Exit(1)
	}

	ctx, cancel := signal.NotifyContext(context.Background(), syscall.SIGINT, syscall.SIGTERM)
	defer cancel()

	if err := app.Run(ctx); err != nil {
		fmt.Fprintf(os.Stderr, "run: %v\n", err)
		os.Exit(1)
	}
}
`))

type serviceMainData struct {
	IR          *spec.IRSpec
	Service     spec.IRService
	Components  []ResolvedComponent
	ConfigsCode string
}

// envGoRef converts a spec value that may contain an env var reference to a Go expression.
// "${KAFKA_BROKER_URL}" → `os.Getenv("KAFKA_BROKER_URL")`
// "literal-value"      → `"literal-value"`
func envGoRef(val string) string {
	if strings.HasPrefix(val, "${") && strings.HasSuffix(val, "}") {
		return fmt.Sprintf(`os.Getenv(%q)`, val[2:len(val)-1])
	}
	return fmt.Sprintf("%q", val)
}

// svcHasComponent reports whether svc includes the named component.
// If the service has no explicit components list, all are included.
func svcHasComponent(svc spec.IRService, name string) bool {
	if len(svc.Components) == 0 {
		return true
	}
	for _, c := range svc.Components {
		if c == name {
			return true
		}
	}
	return false
}

// buildServiceConfigsCode generates Go source code that initialises the configs
// map from the IR's complex block configuration (workflows, events, state, graph, tenancy).
// The returned string is embedded verbatim into the service main template and
// formatted later by go/format, so it may contain raw Go expressions like os.Getenv().
func buildServiceConfigsCode(ir *spec.IRSpec, svc spec.IRService) string {
	var lines []string
	lines = append(lines, "configs := map[string]spec.ComponentConfig{}")

	// Temporal (foundry-temporal) — from workflows: block
	if ir.Workflows != nil && svcHasComponent(svc, "foundry-temporal") {
		wfNames := make([]string, len(ir.Workflows.Workflows))
		for i, wf := range ir.Workflows.Workflows {
			wfNames[i] = fmt.Sprintf("%q", wf.Name)
		}
		host := ir.Workflows.Host
		if host == "" {
			host = "${TEMPORAL_HOST}"
		}
		lines = append(lines, fmt.Sprintf(
			`configs["foundry-temporal"] = spec.ComponentConfig{"namespace": %q, "worker_queue": %q, "host": %s, "workflows": []string{%s}}`,
			ir.Workflows.Namespace,
			ir.Workflows.WorkerQueue,
			envGoRef(host),
			strings.Join(wfNames, ", "),
		))
	}

	// Kafka (foundry-kafka) — from events: block
	if ir.Events != nil && ir.Events.Backend == "kafka" && svcHasComponent(svc, "foundry-kafka") {
		brokerURL := ir.Events.BrokerURL
		if brokerURL == "" && ir.Events.Broker != nil {
			brokerURL = ir.Events.Broker.URL
		}
		topicNames := make([]string, len(ir.Events.Topics))
		for i, t := range ir.Events.Topics {
			topicNames[i] = fmt.Sprintf("%q", t.Name)
		}
		lines = append(lines, fmt.Sprintf(
			`configs["foundry-kafka"] = spec.ComponentConfig{"broker_url": %s, "topics": []string{%s}}`,
			envGoRef(brokerURL),
			strings.Join(topicNames, ", "),
		))
	}

	// NATS (foundry-nats) — from events: block when backend is nats
	if ir.Events != nil && ir.Events.Backend == "nats" && svcHasComponent(svc, "foundry-nats") {
		brokerURL := ir.Events.BrokerURL
		if brokerURL == "" && ir.Events.Broker != nil {
			brokerURL = ir.Events.Broker.URL
		}
		lines = append(lines, fmt.Sprintf(
			`configs["foundry-nats"] = spec.ComponentConfig{"url": %s}`,
			envGoRef(brokerURL),
		))
	}

	// Redis (foundry-redis) — from state: block
	if ir.State != nil && svcHasComponent(svc, "foundry-redis") {
		url := ir.State.URL
		if url == "" && len(ir.State.Backends) > 0 {
			url = ir.State.Backends[0].URL
		}
		keyNames := make([]string, len(ir.State.Keys))
		for i, k := range ir.State.Keys {
			keyNames[i] = fmt.Sprintf("%q", k.Name)
		}
		lines = append(lines, fmt.Sprintf(
			`configs["foundry-redis"] = spec.ComponentConfig{"url": %s, "keys": []string{%s}}`,
			envGoRef(url),
			strings.Join(keyNames, ", "),
		))
	}

	// Apache AGE graph (foundry-graph-age) — from graph: block
	if ir.Graph != nil && ir.Graph.Backend == "age" && svcHasComponent(svc, "foundry-graph-age") {
		nodeLabels := make([]string, len(ir.Graph.NodeTypes))
		for i, n := range ir.Graph.NodeTypes {
			nodeLabels[i] = fmt.Sprintf("%q", n.Label)
		}
		edgeLabels := make([]string, len(ir.Graph.EdgeTypes))
		for i, e := range ir.Graph.EdgeTypes {
			edgeLabels[i] = fmt.Sprintf("%q", e.Label)
		}
		lines = append(lines, fmt.Sprintf(
			`configs["foundry-graph-age"] = spec.ComponentConfig{"graph_name": %q, "node_types": []string{%s}, "edge_types": []string{%s}}`,
			ir.Graph.GraphName,
			strings.Join(nodeLabels, ", "),
			strings.Join(edgeLabels, ", "),
		))
	}

	// Tenancy (foundry-tenancy) — from tenancy: block
	if ir.Tenancy != nil && svcHasComponent(svc, "foundry-tenancy") {
		lines = append(lines, fmt.Sprintf(
			`configs["foundry-tenancy"] = spec.ComponentConfig{"field": %q, "strategy": %q, "header": %q}`,
			ir.Tenancy.Field,
			ir.Tenancy.Strategy,
			ir.Tenancy.Header,
		))
	}

	return strings.Join(lines, "\n\t")
}

func (g *Generator) writeServiceMains(ir *spec.IRSpec, components []ResolvedComponent) error {
	if len(ir.Services) == 0 {
		return nil
	}

	// Build component lookup by name for filtering per-service components.
	compByName := map[string]ResolvedComponent{}
	for _, c := range components {
		compByName[c.Name] = c
	}

	for _, svc := range ir.Services {
		// Select components for this service (subset or all).
		var svcComponents []ResolvedComponent
		if len(svc.Components) == 0 {
			svcComponents = components
		} else {
			for _, name := range svc.Components {
				if c, ok := compByName[name]; ok {
					svcComponents = append(svcComponents, c)
				}
			}
		}
		svcComponents = sortComponents(svcComponents)

		data := serviceMainData{
			IR:          ir,
			Service:     svc,
			Components:  svcComponents,
			ConfigsCode: buildServiceConfigsCode(ir, svc),
		}

		var buf bytes.Buffer
		if err := serviceMainTemplate.Execute(&buf, data); err != nil {
			return fmt.Errorf("rendering main_%s.go: %w", svc.Name, err)
		}
		formatted, err := format.Source(buf.Bytes())
		if err != nil {
			return fmt.Errorf("formatting main_%s.go: %w\nsource:\n%s", svc.Name, err, buf.String())
		}
		filename := "main_" + toSnakeCase(svc.Name) + ".go"
		if err := os.WriteFile(filepath.Join(g.outputDir, filename), formatted, 0644); err != nil {
			return fmt.Errorf("writing %s: %w", filename, err)
		}
	}
	return nil
}

var dockerComposeTemplate = template.Must(template.New("compose").Parse(`# Code generated by forge compile. DO NOT EDIT.
# Spec: {{ .IR.Metadata.Name }} v{{ .IR.Metadata.Version }}
version: "3.9"
services:
{{ range .IR.Services }}  {{ .Name }}:
    build: .
    command: ["/app-{{ .Name }}"]
{{ if .Port }}    ports:
      - "{{ .Port }}:{{ .Port }}"
{{ end }}    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/{{ $.IR.Metadata.Name }}
    depends_on:
      - postgres

{{ end }}  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: {{ .IR.Metadata.Name }}
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
`))

type dockerComposeData struct {
	IR *spec.IRSpec
}

func (g *Generator) writeDockerCompose(ir *spec.IRSpec) error {
	if len(ir.Services) == 0 {
		return nil
	}
	data := dockerComposeData{IR: ir}
	var buf bytes.Buffer
	if err := dockerComposeTemplate.Execute(&buf, data); err != nil {
		return fmt.Errorf("rendering docker-compose.yaml: %w", err)
	}
	return os.WriteFile(filepath.Join(g.outputDir, "docker-compose.yaml"), buf.Bytes(), 0644)
}

// --------------------------------------------------------------------------
// Hooks codegen — generates foundry/types.go + hook_registry.go
// Implements the HOOKS_CONTRACT.md spec (frozen by TSF-Architect, PR #10).
// --------------------------------------------------------------------------

// foundryTypesTemplate generates the foundry/types.go file with HookContext and
// all request/result types used by hook function signatures. This must stay in
// sync with foundry/spec/foundry/types.go (the canonical source of truth).
var foundryTypesTemplate = template.Must(template.New("foundry_types").Parse(`// Code generated by forge compile. DO NOT EDIT.
// Foundry hook shared types — implementing docs/HOOKS_CONTRACT.md
// Canonical source: github.com/jsell-rh/trusted-software-foundry/foundry/spec/foundry
package foundry

import (
	"context"
	"net/http"
	"time"
)

// HookContext is passed to every hook function. It carries operation context,
// a structured logger, and request-scoped metadata.
type HookContext struct {
	Ctx       context.Context
	Logger    Logger
	Tracer    Tracer
	AppName   string
	TenantID  string
	RequestID string
	TraceID   string
	Claims    map[string]any
}

// Logger is a minimal structured logging interface. Arguments are alternating
// key-value pairs: Info("msg", "key1", "val1", "key2", "val2").
type Logger interface {
	Info(msg string, keyvals ...string)
	Warn(msg string, keyvals ...string)
	Error(msg string, keyvals ...string)
	Debug(msg string, keyvals ...string)
}

// Tracer wraps OpenTelemetry tracing.
type Tracer interface {
	Start(ctx context.Context, spanName string) (context.Context, Span)
}

// Span is an OpenTelemetry span.
type Span interface {
	End()
	SetAttribute(key string, value any)
	RecordError(err error)
}

// PostHandlerRequest carries the response details available after the handler runs.
type PostHandlerRequest struct {
	// Method and Path of the handled request.
	Method string
	Path   string

	// StatusCode is the HTTP status code that was written.
	StatusCode int

	// ResponseBytes is the number of bytes written to the response body.
	ResponseBytes int64

	// Duration is the time taken by the handler (excluding this hook).
	Duration time.Duration

	// RequestHeaders are the incoming request headers.
	RequestHeaders http.Header
}

// DBOperation describes a database operation about to execute.
type DBOperation struct {
	Resource   string
	Type       string         // "create", "read", "update", "delete", "list"
	ResourceID string
	Payload    map[string]any // mutable for create/update
	Filter     map[string]any
}

// DBResult carries the outcome of a completed database operation.
type DBResult struct {
	Resource     string
	Operation    string
	ID           string
	RowsAffected int64
	Error        error
}

// EventMessage is the message being published to the event bus.
type EventMessage struct {
	Topic   string
	Key     string
	Payload []byte
	Headers map[string]string
}

// ConsumedEvent is the event received from the event bus.
type ConsumedEvent struct {
	Topic   string
	Key     string
	Payload map[string]any // pre-parsed JSON payload
	Headers map[string]string
	Offset  int64
}
`))

func (g *Generator) writeFoundryTypes(ir *spec.IRSpec) error {
	if len(ir.Hooks) == 0 {
		return nil
	}
	foundryDir := filepath.Join(g.outputDir, "foundry")
	if err := os.MkdirAll(foundryDir, 0755); err != nil {
		return fmt.Errorf("creating foundry/ dir: %w", err)
	}
	var buf bytes.Buffer
	if err := foundryTypesTemplate.Execute(&buf, nil); err != nil {
		return fmt.Errorf("rendering foundry/types.go: %w", err)
	}
	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return fmt.Errorf("formatting foundry/types.go: %w", err)
	}
	return os.WriteFile(filepath.Join(foundryDir, "types.go"), formatted, 0644)
}

// hookRegistryTemplate generates the call site dispatch code in hook_registry.go.
// Each hook entry produces a typed call site matching the HOOKS_CONTRACT.md signatures.
var hookRegistryTemplate = template.Must(template.New("hook_registry").Funcs(template.FuncMap{
	"funcName": hookFuncName,
	"callSite": hookCallSite,
}).Parse(`// Code generated by forge compile. DO NOT EDIT.
// Hook registry — call sites for: {{ .IR.Metadata.Name }} v{{ .IR.Metadata.Version }}
// Human hook implementations are in hooks/*.go — never edit call sites.
// Implements docs/HOOKS_CONTRACT.md (frozen by TSF-Architect).
package main

import (
	"net/http"

	"github.com/jsell-rh/trusted-software-foundry/foundry/spec/foundry"
	"{{ .AppModule }}/hooks"
)

{{ range .Hooks }}// {{ funcName . }} is the generated call site for hook "{{ .Name }}" at point {{ .Point }}.
// Implementation file: {{ .Implementation }}
func {{ funcName . }}({{ callSite . "sig" }}) error {
	return hooks.{{ funcName . }}({{ callSite . "call" }})
}

{{ end }}
`))

// hookFuncName returns the PascalCase function name for a hook.
// Hook name "audit-log" + point "pre-handler" → "AuditLogPreHandler"
func hookFuncName(h spec.IRHook) string {
	name := toPascalCase(h.Name)
	point := toPascalCase(h.Point)
	return name + point
}

// hookCallSite returns the parameter signature or argument list for a hook call site.
// mode "sig" = parameter declarations; mode "call" = argument list.
func hookCallSite(h spec.IRHook, mode string) string {
	switch h.Point {
	case "pre-handler":
		if mode == "sig" {
			return "hctx *foundry.HookContext, w http.ResponseWriter, r *http.Request"
		}
		return "hctx, w, r"
	case "post-handler":
		if mode == "sig" {
			return "hctx *foundry.HookContext, req *foundry.PostHandlerRequest"
		}
		return "hctx, req"
	case "pre-db":
		if mode == "sig" {
			return "hctx *foundry.HookContext, op *foundry.DBOperation"
		}
		return "hctx, op"
	case "post-db":
		if mode == "sig" {
			return "hctx *foundry.HookContext, result *foundry.DBResult"
		}
		return "hctx, result"
	case "pre-publish":
		if mode == "sig" {
			return "hctx *foundry.HookContext, msg *foundry.EventMessage"
		}
		return "hctx, msg"
	case "post-consume":
		if mode == "sig" {
			return "hctx *foundry.HookContext, event *foundry.ConsumedEvent"
		}
		return "hctx, event"
	default:
		if mode == "sig" {
			return "hctx *foundry.HookContext"
		}
		return "hctx"
	}
}

type hookRegistryData struct {
	IR        *spec.IRSpec
	Hooks     []spec.IRHook
	AppModule string
}

func (g *Generator) writeHookRegistry(ir *spec.IRSpec, appModule string) error {
	if len(ir.Hooks) == 0 {
		return nil
	}
	data := hookRegistryData{
		IR:        ir,
		Hooks:     ir.Hooks,
		AppModule: appModule,
	}
	var buf bytes.Buffer
	if err := hookRegistryTemplate.Execute(&buf, data); err != nil {
		return fmt.Errorf("rendering hook_registry.go: %w", err)
	}
	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return fmt.Errorf("formatting hook_registry.go: %w\nsource:\n%s", err, buf.String())
	}
	return os.WriteFile(filepath.Join(g.outputDir, "hook_registry.go"), formatted, 0644)
}

// --------------------------------------------------------------------------
// authz/schema.zed stub — skeleton SpiceDB schema for human completion
// --------------------------------------------------------------------------

// writeAuthzSchemaStub generates a starter SpiceDB schema at the path declared
// in the authz block (e.g. authz/schema.zed). The stub defines one definition
// per authz relation and is intended as a scaffold for engineers to fill in.
// If the file already exists, it is not overwritten so that engineer edits are preserved.
func (g *Generator) writeAuthzSchemaStub(ir *spec.IRSpec) error {
	if ir.Authz == nil || ir.Authz.SchemaFile == "" {
		return nil
	}
	dest := filepath.Join(g.outputDir, ir.Authz.SchemaFile)

	// Do not overwrite an existing schema — preserve engineer edits.
	if _, err := os.Stat(dest); err == nil {
		return nil
	}

	if err := os.MkdirAll(filepath.Dir(dest), 0755); err != nil {
		return fmt.Errorf("creating authz dir: %w", err)
	}

	// Collect unique resource and subject types from relations.
	seen := map[string]bool{}
	var defs []string
	addDef := func(name string) {
		if !seen[name] {
			seen[name] = true
			defs = append(defs, name)
		}
	}
	for _, r := range ir.Authz.Relations {
		if r.Resource != "" {
			addDef(strings.ToLower(r.Resource))
		}
		if r.Subject != "" {
			addDef(strings.ToLower(r.Subject))
		}
	}

	var buf bytes.Buffer
	buf.WriteString("// SpiceDB schema — generated stub by forge compile. Fill in permissions.\n")
	buf.WriteString("// Spec: " + ir.Metadata.Name + " v" + ir.Metadata.Version + "\n\n")

	for _, def := range defs {
		buf.WriteString("definition " + def + " {}\n\n")
	}

	// Re-emit relation structure as commented guidance.
	if len(ir.Authz.Relations) > 0 {
		buf.WriteString("// Declared relations (replace stub definitions above with full schema):\n")
		for _, r := range ir.Authz.Relations {
			buf.WriteString(fmt.Sprintf("//   %s.%s -> %s\n", r.Resource, r.Relation, r.Subject))
		}
	}

	return os.WriteFile(dest, buf.Bytes(), 0644)
}

// copyHookFiles copies all declared hooks/*.go source files into the generated project.
// Hook files are human-written and must be copied unchanged — the compiler never modifies them.
// If a hook file does not yet exist on disk, it is skipped gracefully (engineers write it later).
//
// specDir is the directory that contains the spec file; hook implementation paths declared
// in the spec are resolved relative to it. Pass an empty string to resolve from the CWD.
//
// Returns the subset of hooks whose implementation files were NOT found on disk (missing hooks).
// These are passed to writeHookStubs so that the generated project compiles immediately.
func copyHookFiles(ir *spec.IRSpec, outputDir, specDir string) ([]spec.IRHook, error) {
	if len(ir.Hooks) == 0 {
		return nil, nil
	}
	var missing []spec.IRHook
	for _, h := range ir.Hooks {
		if h.Implementation == "" {
			missing = append(missing, h)
			continue
		}
		// Resolve the source path relative to the spec file's directory.
		srcPath := h.Implementation
		if specDir != "" && !filepath.IsAbs(srcPath) {
			srcPath = filepath.Join(specDir, srcPath)
		}
		data, err := os.ReadFile(srcPath)
		if err != nil {
			// Hook file not yet written by engineers — generate a stub instead.
			missing = append(missing, h)
			continue
		}
		dest := filepath.Join(outputDir, h.Implementation)
		if err := os.MkdirAll(filepath.Dir(dest), 0755); err != nil {
			return nil, fmt.Errorf("creating dir for %s: %w", h.Implementation, err)
		}
		if err := os.WriteFile(dest, data, 0644); err != nil {
			return nil, fmt.Errorf("copying %s: %w", h.Implementation, err)
		}
	}
	return missing, nil
}

// hookStubTemplate generates hooks/stubs_generated.go — stub implementations for every
// hook whose real file was not found on disk. The generated project compiles immediately;
// engineers replace the stubs with real logic as they build the application.
var hookStubTemplate = template.Must(template.New("hook_stubs").Funcs(template.FuncMap{
	"funcName": hookFuncName,
	"callSite": hookCallSite,
}).Parse(`// Code generated by forge compile. DO NOT EDIT.
// Stub implementations for hooks declared in the spec but not yet implemented.
// Replace each function body with your real logic. When you have a real implementation,
// move it to the path declared in app.foundry.yaml and re-run forge compile.
package hooks

import (
	"net/http"

	"github.com/jsell-rh/trusted-software-foundry/foundry/spec/foundry"
)

{{ range . }}// {{ funcName . }} is a generated stub for hook "{{ .Name }}" at point {{ .Point }}.
// TODO: implement this hook. Implementation path declared in spec: {{ .Implementation }}
func {{ funcName . }}({{ callSite . "sig" }}) error {
	return nil
}

{{ end }}
`))

// writeHookStubs generates hooks/stubs_generated.go for hooks whose real files are missing.
// This ensures the generated project's hooks package is importable and compiles immediately.
func (g *Generator) writeHookStubs(missing []spec.IRHook) error {
	if len(missing) == 0 {
		return nil
	}
	hooksDir := filepath.Join(g.outputDir, "hooks")
	if err := os.MkdirAll(hooksDir, 0755); err != nil {
		return fmt.Errorf("creating hooks/ dir: %w", err)
	}
	var buf bytes.Buffer
	if err := hookStubTemplate.Execute(&buf, missing); err != nil {
		return fmt.Errorf("rendering hook stubs: %w", err)
	}
	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return fmt.Errorf("formatting hooks/stubs_generated.go: %w\nsource:\n%s", err, buf.String())
	}
	return os.WriteFile(filepath.Join(hooksDir, "stubs_generated.go"), formatted, 0644)
}
