package compiler

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"

	"github.com/jsell-rh/trusted-software-foundry/foundry/spec"
)

// helmFuncMap provides Go template functions needed by the Helm generation templates.
// Note: these are Go-side functions used during chart generation (not Helm/Sprig functions).
var helmFuncMap = template.FuncMap{
	// replace mimics Helm's replace function for use in Go template context.
	"replace": func(old, new, s string) string { return strings.ReplaceAll(s, old, new) },
}

// --------------------------------------------------------------------------
// Helm chart generation — forge deploy --helm
//
// Generates a production-ready Helm chart in deploy/helm/<app-name>/ with:
//   Chart.yaml         — chart metadata (name, version, appVersion)
//   values.yaml        — all configurable parameters with sensible defaults
//   templates/
//     _helpers.tpl     — common label helpers
//     deployment.yaml  — Deployment template per service
//     service.yaml     — Service template per service
//     secrets.yaml     — Secret template
//     NOTES.txt        — post-install usage instructions
// --------------------------------------------------------------------------

// GenerateHelm generates a Helm chart for the spec into outputDir/deploy/helm/<appName>/.
func GenerateHelm(ir *spec.IRSpec, outputDir string) error {
	appName := strings.ReplaceAll(ir.Metadata.Name, " ", "-")
	chartDir := filepath.Join(outputDir, "deploy", "helm", appName)
	templatesDir := filepath.Join(chartDir, "templates")

	for _, dir := range []string{chartDir, templatesDir} {
		if err := os.MkdirAll(dir, 0755); err != nil {
			return fmt.Errorf("creating %s: %w", dir, err)
		}
	}

	info := helmChartData(ir)
	vals := helmValuesData(ir)

	if err := writeHelmFile(chartDir, "Chart.yaml", helmChartTemplate, info); err != nil {
		return fmt.Errorf("Chart.yaml: %w", err)
	}
	if err := writeHelmFile(chartDir, "values.yaml", helmValuesTemplate, vals); err != nil {
		return fmt.Errorf("values.yaml: %w", err)
	}
	if err := writeHelmHelpers(templatesDir, info.AppName); err != nil {
		return fmt.Errorf("templates/_helpers.tpl: %w", err)
	}
	if len(ir.Services) > 0 {
		// Multi-service: generate per-service deployment and service files.
		for _, svc := range vals.Services {
			svcVals := helmValuesInfo{AppName: vals.AppName, Services: []helmServiceInfo{svc}, EnvVarKeys: vals.EnvVarKeys}
			if err := writeHelmFile(templatesDir, svc.Name+"-deployment.yaml", helmDeploymentTemplate, svcVals); err != nil {
				return fmt.Errorf("templates/%s-deployment.yaml: %w", svc.Name, err)
			}
			if err := writeHelmFile(templatesDir, svc.Name+"-service.yaml", helmServiceTemplate, svcVals); err != nil {
				return fmt.Errorf("templates/%s-service.yaml: %w", svc.Name, err)
			}
		}
	} else {
		if err := writeHelmFile(templatesDir, "deployment.yaml", helmDeploymentTemplate, vals); err != nil {
			return fmt.Errorf("templates/deployment.yaml: %w", err)
		}
		if err := writeHelmFile(templatesDir, "service.yaml", helmServiceTemplate, vals); err != nil {
			return fmt.Errorf("templates/service.yaml: %w", err)
		}
	}
	if err := writeHelmFile(templatesDir, "secret.yaml", helmSecretTemplate, vals); err != nil {
		return fmt.Errorf("templates/secret.yaml: %w", err)
	}
	if err := writeHelmFile(templatesDir, "NOTES.txt", helmNotesTemplate, info); err != nil {
		return fmt.Errorf("templates/NOTES.txt: %w", err)
	}

	return nil
}

func writeHelmFile(dir, name string, tmpl *template.Template, data any) error {
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return fmt.Errorf("rendering %s: %w", name, err)
	}
	return os.WriteFile(filepath.Join(dir, name), buf.Bytes(), 0644)
}

// writeHelmHelpers writes _helpers.tpl as a raw Helm template (not processed by Go's
// text/template) since it contains Helm/Sprig functions not known to Go's template engine.
func writeHelmHelpers(templatesDir, appName string) error {
	content := `{{/* Generated by forge deploy --helm */}}

{{/*
Expand the name of the chart.
*/}}
{{- define "` + appName + `.name" -}}
{{- default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" }}
{{- end }}

{{/*
Create a default fully qualified app name.
*/}}
{{- define "` + appName + `.fullname" -}}
{{- if .Values.fullnameOverride }}
{{- .Values.fullnameOverride | trunc 63 | trimSuffix "-" }}
{{- else }}
{{- $name := default .Chart.Name .Values.nameOverride }}
{{- if contains $name .Release.Name }}
{{- .Release.Name | trunc 63 | trimSuffix "-" }}
{{- else }}
{{- printf "%s-%s" .Release.Name $name | trunc 63 | trimSuffix "-" }}
{{- end }}
{{- end }}
{{- end }}

{{/*
Common labels
*/}}
{{- define "` + appName + `.labels" -}}
helm.sh/chart: {{ include "` + appName + `.chart" . }}
{{ include "` + appName + `.selectorLabels" . }}
{{- if .Chart.AppVersion }}
app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
{{- end }}
app.kubernetes.io/managed-by: {{ .Release.Service }}
managed-by: forge
{{- end }}

{{/*
Selector labels
*/}}
{{- define "` + appName + `.selectorLabels" -}}
app.kubernetes.io/name: {{ include "` + appName + `.name" . }}
app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}

{{/*
Chart label
*/}}
{{- define "` + appName + `.chart" -}}
{{- printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}
{{- end }}
`
	return os.WriteFile(filepath.Join(templatesDir, "_helpers.tpl"), []byte(content), 0644)
}

// --------------------------------------------------------------------------
// Template data types
// --------------------------------------------------------------------------

type helmChartInfo struct {
	AppName     string
	Version     string
	Description string
}

type helmServiceInfo struct {
	Name      string
	Port      int
	HasHealth bool
}

type helmValuesInfo struct {
	AppName    string
	Version    string
	Services   []helmServiceInfo
	EnvVarKeys []string // secret key names needed (e.g. "database-url")
}

func helmChartData(ir *spec.IRSpec) helmChartInfo {
	return helmChartInfo{
		AppName:     strings.ReplaceAll(ir.Metadata.Name, " ", "-"),
		Version:     ir.Metadata.Version,
		Description: ir.Metadata.Description,
	}
}

func helmValuesData(ir *spec.IRSpec) helmValuesInfo {
	appName := strings.ReplaceAll(ir.Metadata.Name, " ", "-")

	var services []helmServiceInfo
	if len(ir.Services) > 0 {
		for _, svc := range ir.Services {
			services = append(services, helmServiceInfo{
				Name:      svc.Name,
				Port:      svc.Port,
				HasHealth: svcHasComponent(svc, "foundry-health"),
			})
		}
	} else {
		services = []helmServiceInfo{{Name: appName, Port: 8080, HasHealth: true}}
	}

	// Collect unique secret key names from the global env vars.
	globalEnvVars := buildEnvVars(ir, spec.IRService{})
	var keys []string
	for _, v := range globalEnvVars {
		if !v.IsLiteral {
			keys = append(keys, v.SecretKey)
		}
	}

	return helmValuesInfo{
		AppName:    appName,
		Version:    ir.Metadata.Version,
		Services:   services,
		EnvVarKeys: keys,
	}
}

// --------------------------------------------------------------------------
// Helm templates
// --------------------------------------------------------------------------

var helmChartTemplate = template.Must(template.New("chart").Parse(`# Generated by forge deploy --helm. DO NOT EDIT.
apiVersion: v2
name: {{ .AppName }}
description: {{ if .Description }}{{ .Description }}{{ else }}{{ .AppName }} — compiled by Trusted Software Foundry{{ end }}
type: application
version: 0.1.0
appVersion: {{ printf "%q" .Version }}
keywords:
  - trusted-software-foundry
  - forge
`))

var helmValuesTemplate = template.Must(template.New("values").Parse(`# Generated by forge deploy --helm. Tune for your environment.
# Spec: {{ .AppName }} v{{ .Version }}

replicaCount: 1

image:
  repository: ""  # Override with your registry/image path
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

securityContext:
  runAsNonRoot: true
  runAsUser: 1001

# Services declared in the spec.
services:
{{ range .Services }}  {{ .Name }}:
    image: {{ $.AppName }}-{{ .Name }}:latest
    port: {{ if .Port }}{{ .Port }}{{ else }}8080{{ end }}
    replicaCount: 1
{{ end }}
# Secret values — fill in before deploying.
# Use: kubectl create secret generic {{ .AppName }}-secrets \
#   --from-literal=database-url='postgres://...'
secrets:
{{ range .EnvVarKeys }}  {{ . }}: ""  # base64-encoded or literal value
{{ end }}
`))

var helmDeploymentTemplate = template.Must(template.New("hdeployment").Funcs(helmFuncMap).Parse(`{{/* Generated by forge deploy --helm. */}}
{{ range .Services -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ "{{" }} include "{{ $.AppName }}.fullname" . {{ "}}" }}-{{ .Name }}
  labels:
    {{- "{{" }} include "{{ $.AppName }}.labels" . | nindent 4 {{ "}}" }}
    app.kubernetes.io/component: {{ .Name }}
spec:
  replicas: {{ "{{" }} .Values.services.{{ .Name | replace "-" "_" }}.replicaCount | default .Values.replicaCount {{ "}}" }}
  selector:
    matchLabels:
      {{- "{{" }} include "{{ $.AppName }}.selectorLabels" . | nindent 6 {{ "}}" }}
      app.kubernetes.io/component: {{ .Name }}
  template:
    metadata:
      labels:
        {{- "{{" }} include "{{ $.AppName }}.selectorLabels" . | nindent 8 {{ "}}" }}
        app.kubernetes.io/component: {{ .Name }}
    spec:
      securityContext:
        runAsNonRoot: {{ "{{" }} .Values.securityContext.runAsNonRoot {{ "}}" }}
        runAsUser: {{ "{{" }} .Values.securityContext.runAsUser {{ "}}" }}
      containers:
        - name: {{ .Name }}
          image: "{{ "{{" }} .Values.services.{{ .Name | replace "-" "_" }}.image {{ "}}" }}"
          imagePullPolicy: {{ "{{" }} .Values.image.pullPolicy {{ "}}" }}
{{ if .Port }}          ports:
            - name: http
              containerPort: {{ .Port }}
              protocol: TCP
{{ end -}}
{{ if .HasHealth }}          livenessProbe:
            httpGet:
              path: /healthz
              port: 8083
            initialDelaySeconds: 15
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8083
            initialDelaySeconds: 5
            periodSeconds: 10
{{ end -}}
          resources:
            {{- "{{" }} toYaml .Values.resources | nindent 12 {{ "}}" }}
          envFrom:
            - secretRef:
                name: {{ "{{" }} include "{{ $.AppName }}.fullname" . {{ "}}" }}-secrets
{{ end -}}
`))

var helmServiceTemplate = template.Must(template.New("hservice").Parse(`{{/* Generated by forge deploy --helm. */}}
{{ range .Services -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ "{{" }} include "{{ $.AppName }}.fullname" . {{ "}}" }}-{{ .Name }}
  labels:
    {{- "{{" }} include "{{ $.AppName }}.labels" . | nindent 4 {{ "}}" }}
    app.kubernetes.io/component: {{ .Name }}
spec:
  type: ClusterIP
  selector:
    {{- "{{" }} include "{{ $.AppName }}.selectorLabels" . | nindent 4 {{ "}}" }}
    app.kubernetes.io/component: {{ .Name }}
{{ if .Port }}  ports:
    - name: http
      port: {{ .Port }}
      targetPort: http
      protocol: TCP
{{ end -}}
{{ end -}}
`))

var helmSecretTemplate = template.Must(template.New("hsecret").Funcs(helmFuncMap).Parse(`{{/* Generated by forge deploy --helm. Fill values.secrets before deploying. */}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ "{{" }} include "{{ $.AppName }}.fullname" . {{ "}}" }}-secrets
  labels:
    {{- "{{" }} include "{{ $.AppName }}.labels" . | nindent 4 {{ "}}" }}
type: Opaque
stringData:
{{ range .EnvVarKeys -}}
  {{ . }}: {{ "{{" }} required "secrets.{{ . }} is required" .Values.secrets.{{ . | replace "-" "_" }} | quote {{ "}}" }}
{{ end -}}
`))

var helmNotesTemplate = template.Must(template.New("notes").Parse(`{{ .AppName }} has been deployed by Trusted Software Foundry.

To check the status of your deployment:

  kubectl get pods -l app.kubernetes.io/name={{ .AppName }}

To view logs for a specific service (e.g. api-server):

  kubectl logs -l app.kubernetes.io/component=api-server

Before your first deployment, create the required secrets:

  kubectl create secret generic {{ .AppName }}-secrets \
    --from-literal=database-url='postgres://user:pass@host:5432/db' \
    # (add other required secret keys)

Generated by forge deploy --helm | Trusted Software Foundry
`))
