package compiler

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/jsell-rh/trusted-software-foundry/foundry/spec"
)

// GenerateOpenAPI writes an openapi.yaml file into outputDir derived from ir.
// The generated spec follows OpenAPI 3.0.3 and includes:
//   - One path per CRUD operation declared in each resource.
//   - Inline schema per resource (properties derived from IRField definitions).
//   - Shared error response schema matching the ServiceError JSON shape.
//   - Pagination envelope for list responses.
func GenerateOpenAPI(ir *spec.IRSpec, outputDir string) error {
	content := buildOpenAPISpec(ir)
	path := filepath.Join(outputDir, "openapi.yaml")
	return os.WriteFile(path, []byte(content), 0644)
}

// buildOpenAPISpec returns the full OpenAPI 3.0.3 YAML document as a string.
func buildOpenAPISpec(ir *spec.IRSpec) string {
	var sb strings.Builder

	basePath := ""
	if ir.API != nil && ir.API.REST != nil {
		basePath = strings.TrimSuffix(ir.API.REST.BasePath, "/")
	}

	appName := ir.Metadata.Name
	if appName == "" {
		appName = "foundry-app"
	}

	// --- Header ---
	sb.WriteString("openapi: \"3.0.3\"\n")
	sb.WriteString("info:\n")
	fmt.Fprintf(&sb, "  title: %q\n", appName)
	sb.WriteString("  version: \"1.0.0\"\n")
	sb.WriteString("  description: \"Generated by Trusted Software Foundry forge compiler\"\n")
	sb.WriteString("\n")

	// --- Servers ---
	sb.WriteString("servers:\n")
	fmt.Fprintf(&sb, "  - url: \"%s\"\n", basePath)
	sb.WriteString("    description: \"Application base path\"\n")
	sb.WriteString("\n")

	// --- Paths ---
	sb.WriteString("paths:\n")
	for _, res := range ir.Resources {
		plural := res.Plural
		if plural == "" {
			plural = strings.ToLower(res.Name) + "s"
		}
		ops := opsMap(res.Operations)
		writeResourcePaths(&sb, res, plural, ops)
	}
	sb.WriteString("\n")

	// --- Components ---
	sb.WriteString("components:\n")
	sb.WriteString("  schemas:\n")

	// ServiceError schema
	writeServiceErrorSchema(&sb)

	// Pagination list envelope template
	for _, res := range ir.Resources {
		writeResourceSchemas(&sb, res)
	}

	return sb.String()
}

// opsMap converts ops slice to set.
func opsMap(ops []string) map[string]bool {
	m := make(map[string]bool, len(ops))
	for _, op := range ops {
		m[op] = true
	}
	return m
}

// writeResourcePaths emits the OpenAPI path objects for a single resource.
func writeResourcePaths(sb *strings.Builder, res spec.IRResource, plural string, ops map[string]bool) {
	name := res.Name

	// --- Collection: /<plural> ---
	hasCollection := ops["list"] || ops["create"]
	if hasCollection {
		fmt.Fprintf(sb, "  /%s:\n", plural)

		if ops["list"] {
			fmt.Fprintf(sb, "    get:\n")
			fmt.Fprintf(sb, "      summary: \"List %s resources\"\n", name)
			fmt.Fprintf(sb, "      operationId: \"list%s\"\n", name)
			fmt.Fprintf(sb, "      tags: [\"%s\"]\n", name)
			sb.WriteString("      parameters:\n")
			sb.WriteString("        - name: page\n")
			sb.WriteString("          in: query\n")
			sb.WriteString("          schema:\n")
			sb.WriteString("            type: integer\n")
			sb.WriteString("            default: 1\n")
			sb.WriteString("            minimum: 1\n")
			sb.WriteString("        - name: size\n")
			sb.WriteString("          in: query\n")
			sb.WriteString("          schema:\n")
			sb.WriteString("            type: integer\n")
			sb.WriteString("            default: 20\n")
			sb.WriteString("            minimum: 1\n")
			sb.WriteString("            maximum: 200\n")
			sb.WriteString("      responses:\n")
			sb.WriteString("        \"200\":\n")
			fmt.Fprintf(sb, "          description: \"Paginated list of %s\"\n", plural)
			sb.WriteString("          content:\n")
			sb.WriteString("            application/json:\n")
			sb.WriteString("              schema:\n")
			fmt.Fprintf(sb, "                $ref: \"#/components/schemas/%sList\"\n", name)
			writeErrorResponses(sb)
		}

		if ops["create"] {
			fmt.Fprintf(sb, "    post:\n")
			fmt.Fprintf(sb, "      summary: \"Create a %s resource\"\n", name)
			fmt.Fprintf(sb, "      operationId: \"create%s\"\n", name)
			fmt.Fprintf(sb, "      tags: [\"%s\"]\n", name)
			sb.WriteString("      requestBody:\n")
			sb.WriteString("        required: true\n")
			sb.WriteString("        content:\n")
			sb.WriteString("          application/json:\n")
			sb.WriteString("            schema:\n")
			fmt.Fprintf(sb, "              $ref: \"#/components/schemas/%sInput\"\n", name)
			sb.WriteString("      responses:\n")
			sb.WriteString("        \"201\":\n")
			fmt.Fprintf(sb, "          description: \"Created %s\"\n", name)
			sb.WriteString("          content:\n")
			sb.WriteString("            application/json:\n")
			sb.WriteString("              schema:\n")
			fmt.Fprintf(sb, "                $ref: \"#/components/schemas/%s\"\n", name)
			writeErrorResponses(sb)
		}
	}

	// --- Item: /<plural>/{id} ---
	hasItem := ops["read"] || ops["update"] || ops["delete"]
	if hasItem {
		fmt.Fprintf(sb, "  /%s/{id}:\n", plural)
		sb.WriteString("    parameters:\n")
		sb.WriteString("      - name: id\n")
		sb.WriteString("        in: path\n")
		sb.WriteString("        required: true\n")
		sb.WriteString("        schema:\n")
		sb.WriteString("          type: string\n")
		sb.WriteString("          format: uuid\n")

		if ops["read"] {
			sb.WriteString("    get:\n")
			fmt.Fprintf(sb, "      summary: \"Get a %s by id\"\n", name)
			fmt.Fprintf(sb, "      operationId: \"get%s\"\n", name)
			fmt.Fprintf(sb, "      tags: [\"%s\"]\n", name)
			sb.WriteString("      responses:\n")
			sb.WriteString("        \"200\":\n")
			fmt.Fprintf(sb, "          description: \"%s\"\n", name)
			sb.WriteString("          content:\n")
			sb.WriteString("            application/json:\n")
			sb.WriteString("              schema:\n")
			fmt.Fprintf(sb, "                $ref: \"#/components/schemas/%s\"\n", name)
			writeErrorResponses(sb)
		}

		if ops["update"] {
			sb.WriteString("    put:\n")
			fmt.Fprintf(sb, "      summary: \"Update a %s by id\"\n", name)
			fmt.Fprintf(sb, "      operationId: \"update%s\"\n", name)
			fmt.Fprintf(sb, "      tags: [\"%s\"]\n", name)
			sb.WriteString("      requestBody:\n")
			sb.WriteString("        required: true\n")
			sb.WriteString("        content:\n")
			sb.WriteString("          application/json:\n")
			sb.WriteString("            schema:\n")
			fmt.Fprintf(sb, "              $ref: \"#/components/schemas/%sInput\"\n", name)
			sb.WriteString("      responses:\n")
			sb.WriteString("        \"200\":\n")
			fmt.Fprintf(sb, "          description: \"Updated %s\"\n", name)
			sb.WriteString("          content:\n")
			sb.WriteString("            application/json:\n")
			sb.WriteString("              schema:\n")
			fmt.Fprintf(sb, "                $ref: \"#/components/schemas/%s\"\n", name)
			writeErrorResponses(sb)
		}

		if ops["delete"] {
			sb.WriteString("    delete:\n")
			fmt.Fprintf(sb, "      summary: \"Delete a %s by id\"\n", name)
			fmt.Fprintf(sb, "      operationId: \"delete%s\"\n", name)
			fmt.Fprintf(sb, "      tags: [\"%s\"]\n", name)
			sb.WriteString("      responses:\n")
			sb.WriteString("        \"204\":\n")
			fmt.Fprintf(sb, "          description: \"%s deleted\"\n", name)
			writeErrorResponses(sb)
		}
	}
}

// writeErrorResponses emits the shared error response entries for a path operation.
func writeErrorResponses(sb *strings.Builder) {
	for _, code := range []string{"400", "401", "403", "404", "409", "500"} {
		desc := errorDesc(code)
		fmt.Fprintf(sb, "        \"%s\":\n", code)
		fmt.Fprintf(sb, "          description: \"%s\"\n", desc)
		sb.WriteString("          content:\n")
		sb.WriteString("            application/json:\n")
		sb.WriteString("              schema:\n")
		sb.WriteString("                $ref: \"#/components/schemas/ServiceError\"\n")
	}
}

func errorDesc(code string) string {
	switch code {
	case "400":
		return "Bad request"
	case "401":
		return "Unauthenticated"
	case "403":
		return "Forbidden"
	case "404":
		return "Not found"
	case "409":
		return "Conflict"
	case "500":
		return "Internal server error"
	default:
		return "Error"
	}
}

// writeServiceErrorSchema emits the ServiceError schema matching foundry/spec/errors.go.
func writeServiceErrorSchema(sb *strings.Builder) {
	sb.WriteString("    ServiceError:\n")
	sb.WriteString("      type: object\n")
	sb.WriteString("      required: [code, http_status, reason]\n")
	sb.WriteString("      properties:\n")
	sb.WriteString("        code:\n")
	sb.WriteString("          type: integer\n")
	sb.WriteString("          description: \"Foundry error code\"\n")
	sb.WriteString("          example: 7\n")
	sb.WriteString("        http_status:\n")
	sb.WriteString("          type: integer\n")
	sb.WriteString("          description: \"HTTP status code\"\n")
	sb.WriteString("          example: 404\n")
	sb.WriteString("        reason:\n")
	sb.WriteString("          type: string\n")
	sb.WriteString("          description: \"Human-readable error message\"\n")
	sb.WriteString("          example: \"Resource not found\"\n")
}

// writeResourceSchemas emits the resource body schema, input schema, and list schema.
func writeResourceSchemas(sb *strings.Builder, res spec.IRResource) {
	name := res.Name

	// --- Resource schema (includes id + auto fields) ---
	fmt.Fprintf(sb, "    %s:\n", name)
	sb.WriteString("      type: object\n")
	writeRequiredFields(sb, res.Fields, true)
	sb.WriteString("      properties:\n")
	sb.WriteString("        id:\n")
	sb.WriteString("          type: string\n")
	sb.WriteString("          format: uuid\n")
	sb.WriteString("          readOnly: true\n")
	for _, f := range res.Fields {
		writeFieldSchema(sb, f, false)
	}

	// --- Input schema (excludes auto/readonly fields) ---
	fmt.Fprintf(sb, "    %sInput:\n", name)
	sb.WriteString("      type: object\n")
	writeRequiredFields(sb, res.Fields, false)
	sb.WriteString("      properties:\n")
	for _, f := range res.Fields {
		writeFieldSchema(sb, f, true)
	}

	// --- List envelope schema ---
	fmt.Fprintf(sb, "    %sList:\n", name)
	sb.WriteString("      type: object\n")
	sb.WriteString("      required: [kind, page, size, total, items]\n")
	sb.WriteString("      properties:\n")
	sb.WriteString("        kind:\n")
	sb.WriteString("          type: string\n")
	fmt.Fprintf(sb, "          example: \"%sList\"\n", name)
	sb.WriteString("        page:\n")
	sb.WriteString("          type: integer\n")
	sb.WriteString("        size:\n")
	sb.WriteString("          type: integer\n")
	sb.WriteString("        total:\n")
	sb.WriteString("          type: integer\n")
	sb.WriteString("        items:\n")
	sb.WriteString("          type: array\n")
	sb.WriteString("          items:\n")
	fmt.Fprintf(sb, "            $ref: \"#/components/schemas/%s\"\n", name)
}

// writeRequiredFields emits the OpenAPI `required` array for a resource.
// When inputOnly is true, auto-populated and soft-delete fields are excluded.
func writeRequiredFields(sb *strings.Builder, fields []spec.IRField, includeID bool) {
	var required []string
	if includeID {
		required = append(required, "id")
	}
	for _, f := range fields {
		if !f.Required {
			continue
		}
		if f.Auto != "" || f.SoftDelete {
			continue
		}
		required = append(required, f.Name)
	}
	if len(required) == 0 {
		return
	}
	sb.WriteString("      required:\n")
	for _, r := range required {
		fmt.Fprintf(sb, "        - %s\n", r)
	}
}

// writeFieldSchema emits the YAML property block for a single IRField.
// When inputOnly is true, readOnly/auto fields are skipped (used for *Input schema).
func writeFieldSchema(sb *strings.Builder, f spec.IRField, inputOnly bool) {
	if inputOnly && (f.Auto != "" || f.SoftDelete) {
		return
	}
	fmt.Fprintf(sb, "        %s:\n", f.Name)
	oaType, oaFormat := irTypeToOpenAPI(f.Type)
	fmt.Fprintf(sb, "          type: %s\n", oaType)
	if oaFormat != "" {
		fmt.Fprintf(sb, "          format: %s\n", oaFormat)
	}
	if f.MaxLength > 0 && f.Type == "string" {
		fmt.Fprintf(sb, "          maxLength: %d\n", f.MaxLength)
	}
	if f.Auto != "" || f.SoftDelete {
		sb.WriteString("          readOnly: true\n")
	}
	if !f.Required || f.Auto != "" {
		sb.WriteString("          nullable: true\n")
	}
}

// irTypeToOpenAPI maps an IRField type string to an OpenAPI type + format pair.
func irTypeToOpenAPI(irType string) (typ, format string) {
	switch irType {
	case "string":
		return "string", ""
	case "int":
		return "integer", "int64"
	case "float":
		return "number", "double"
	case "bool":
		return "boolean", ""
	case "timestamp":
		return "string", "date-time"
	case "uuid":
		return "string", "uuid"
	default:
		return "string", ""
	}
}
