package compiler

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"
)

// Generator writes the wiring code for a compiled TSC application.
// It generates ONLY:
//   - main.go  (component bootstrap)
//   - go.mod   (dependency-locked module)
//   - migrations/<name>.sql  (one file per resource)
//
// It never generates business logic, handler implementations, or service code.
type Generator struct {
	outputDir string
}

// NewGenerator creates a Generator that writes into outputDir.
func NewGenerator(outputDir string) *Generator {
	return &Generator{outputDir: outputDir}
}

// Generate writes all output files for the given spec and resolved components.
func (g *Generator) Generate(spec *Spec, components []ResolvedComponent) error {
	if err := os.MkdirAll(g.outputDir, 0755); err != nil {
		return fmt.Errorf("creating output directory %q: %w", g.outputDir, err)
	}

	if err := g.writeMainGo(spec, components); err != nil {
		return fmt.Errorf("generating main.go: %w", err)
	}
	if err := g.writeGoMod(spec, components); err != nil {
		return fmt.Errorf("generating go.mod: %w", err)
	}
	if err := g.writeMigrations(spec); err != nil {
		return fmt.Errorf("generating migrations: %w", err)
	}
	return nil
}

// --------------------------------------------------------------------------
// main.go
// --------------------------------------------------------------------------

var mainGoTemplate = template.Must(template.New("main").Parse(`// Code generated by tsc compiler. DO NOT EDIT.
// Spec: {{ .Spec.Metadata.Name }} {{ .Spec.Metadata.Version }}
// Components: {{ .ComponentList }}
package main

import (
	"fmt"
	"os"

	tscapp "github.com/openshift-online/tsc-components/app"
{{ range .Components }}	{{ .ImportAlias }} "{{ .Module }}"
{{ end }})

func main() {
	app := tscapp.New()

	// Register trusted components (order matters — dependencies first)
{{ range .Components }}	app.Register({{ .ImportAlias }}.New())
{{ end }}
	// Configure from environment
	app.SetName("{{ .Spec.Metadata.Name }}")

{{ if .Spec.API.REST.BasePath }}	app.SetRESTBasePath("{{ .Spec.API.REST.BasePath }}")
{{ end }}{{ if .Spec.Auth.JWKUrl }}	app.SetJWKURL(envOrDefault("JWK_CERT_URL", "{{ .Spec.Auth.JWKUrl }}"))
{{ end }}{{ if .Spec.Observability.HealthCheck.Port }}	app.SetHealthPort({{ .Spec.Observability.HealthCheck.Port }})
{{ end }}{{ if .Spec.Observability.Metrics.Port }}	app.SetMetricsPort({{ .Spec.Observability.Metrics.Port }})
{{ end }}
	if err := app.Start(); err != nil {
		fmt.Fprintf(os.Stderr, "fatal: %v\n", err)
		os.Exit(1)
	}
}

func envOrDefault(key, def string) string {
	if v := os.Getenv(key); v != "" {
		return v
	}
	return def
}
`))

type mainGoData struct {
	Spec          *Spec
	Components    []componentImport
	ComponentList string
}

type componentImport struct {
	ImportAlias string
	Module      string
}

func (g *Generator) writeMainGo(spec *Spec, components []ResolvedComponent) error {
	imports := make([]componentImport, len(components))
	names := make([]string, len(components))
	for i, c := range components {
		// Derive a clean import alias from the component name: "tsc-http" → "tschttp"
		alias := strings.ReplaceAll(strings.ReplaceAll(c.Name, "tsc-", "tsc"), "-", "")
		imports[i] = componentImport{
			ImportAlias: alias,
			Module:      c.Module,
		}
		names[i] = c.Name + "@" + c.Version
	}

	data := mainGoData{
		Spec:          spec,
		Components:    imports,
		ComponentList: strings.Join(names, ", "),
	}

	var buf bytes.Buffer
	if err := mainGoTemplate.Execute(&buf, data); err != nil {
		return fmt.Errorf("rendering main.go template: %w", err)
	}

	return os.WriteFile(filepath.Join(g.outputDir, "main.go"), buf.Bytes(), 0644)
}

// --------------------------------------------------------------------------
// go.mod
// --------------------------------------------------------------------------

var goModTemplate = template.Must(template.New("gomod").Parse(`// Code generated by tsc compiler. DO NOT EDIT.
module {{ .AppModule }}

go 1.24.0

require (
	github.com/openshift-online/tsc-components/app v0.1.0
{{ range .Components }}	{{ .Module }} {{ .Version }}
{{ end }})
`))

type goModData struct {
	AppModule  string
	Components []goModComponent
}

type goModComponent struct {
	Module  string
	Version string
}

func (g *Generator) writeGoMod(spec *Spec, components []ResolvedComponent) error {
	// Derive a Go module path from the application name.
	appModule := "github.com/openshift-online/" + strings.ReplaceAll(spec.Metadata.Name, " ", "-")

	mods := make([]goModComponent, len(components))
	for i, c := range components {
		mods[i] = goModComponent{
			Module:  c.Module,
			Version: c.Version,
		}
	}

	data := goModData{
		AppModule:  appModule,
		Components: mods,
	}

	var buf bytes.Buffer
	if err := goModTemplate.Execute(&buf, data); err != nil {
		return fmt.Errorf("rendering go.mod template: %w", err)
	}

	return os.WriteFile(filepath.Join(g.outputDir, "go.mod"), buf.Bytes(), 0644)
}

// --------------------------------------------------------------------------
// migrations/
// --------------------------------------------------------------------------

var migrationTemplate = template.Must(template.New("migration").Parse(`-- Code generated by tsc compiler. DO NOT EDIT.
-- Resource: {{ .Resource.Name }}
CREATE TABLE IF NOT EXISTS {{ .TableName }} (
    id         VARCHAR(32)  NOT NULL,
    created_at TIMESTAMP    NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP    NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMP,
{{ range .Columns }}    {{ .ColumnName }} {{ .SQLType }}{{ if .NotNull }} NOT NULL{{ end }},
{{ end }}    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_{{ .TableName }}_deleted_at ON {{ .TableName }} (deleted_at);
`))

type migrationData struct {
	Resource  Resource
	TableName string
	Columns   []migrationColumn
}

type migrationColumn struct {
	ColumnName string
	SQLType    string
	NotNull    bool
}

func (g *Generator) writeMigrations(spec *Spec) error {
	migrDir := filepath.Join(g.outputDir, "migrations")
	if err := os.MkdirAll(migrDir, 0755); err != nil {
		return fmt.Errorf("creating migrations directory: %w", err)
	}

	for i, res := range spec.Resources {
		tableName := strings.ToLower(res.Plural)
		if tableName == "" {
			tableName = strings.ToLower(res.Name) + "s"
		}

		cols := make([]migrationColumn, 0, len(res.Fields))
		for _, f := range res.Fields {
			// Skip auto-managed fields — they are already in the base table definition.
			if f.Auto == "created" || f.Auto == "updated" || f.SoftDelete {
				continue
			}
			cols = append(cols, migrationColumn{
				ColumnName: strings.ToLower(f.Name),
				SQLType:    goTypeToSQL(f.Type, f.MaxLength),
				NotNull:    f.Required,
			})
		}

		data := migrationData{
			Resource:  res,
			TableName: tableName,
			Columns:   cols,
		}

		var buf bytes.Buffer
		if err := migrationTemplate.Execute(&buf, data); err != nil {
			return fmt.Errorf("rendering migration for %q: %w", res.Name, err)
		}

		// Zero-pad sequence for deterministic ordering.
		filename := fmt.Sprintf("%04d_%s.sql", i+1, tableName)
		if err := os.WriteFile(filepath.Join(migrDir, filename), buf.Bytes(), 0644); err != nil {
			return fmt.Errorf("writing migration file %q: %w", filename, err)
		}
	}

	return nil
}

// goTypeToSQL maps IR field types to PostgreSQL column types.
func goTypeToSQL(irType string, maxLen int) string {
	switch irType {
	case "string":
		if maxLen > 0 {
			return fmt.Sprintf("VARCHAR(%d)", maxLen)
		}
		return "TEXT"
	case "int", "integer":
		return "INTEGER"
	case "int64":
		return "BIGINT"
	case "bool", "boolean":
		return "BOOLEAN"
	case "timestamp":
		return "TIMESTAMP"
	case "float", "float64":
		return "DOUBLE PRECISION"
	default:
		return "TEXT"
	}
}
