package compiler

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strings"
	"text/template"

	"github.com/jsell-rh/trusted-software-foundry/tsc/spec"
)

// --------------------------------------------------------------------------
// Multi-service codegen — generates main_<service>.go + docker-compose.yaml
// --------------------------------------------------------------------------

// toPascalCase converts a kebab-case name to PascalCase.
// "api-server" → "ApiServer", "worker" → "Worker"
func toPascalCase(s string) string {
	parts := strings.Split(s, "-")
	var sb strings.Builder
	for _, p := range parts {
		if len(p) > 0 {
			sb.WriteString(strings.ToUpper(p[:1]) + p[1:])
		}
	}
	return sb.String()
}

// toSnakeCase converts a kebab-case name to snake_case for file names.
// "api-server" → "api_server"
func toSnakeCase(s string) string {
	return strings.ReplaceAll(s, "-", "_")
}

var serviceMainTemplate = template.Must(template.New("svcmain").Funcs(template.FuncMap{
	"cleanAlias": func(name string) string {
		return strings.ReplaceAll(name, "-", "")
	},
	"pascal": toPascalCase,
}).Parse(`// Code generated by forge compile. DO NOT EDIT.
// Service: {{ .Service.Name }} (role: {{ .Service.Role }})
// Spec: {{ .IR.Metadata.Name }} v{{ .IR.Metadata.Version }}
package main

import (
	"context"
	"fmt"
	"os"
	"os/signal"
	"syscall"

	"github.com/jsell-rh/trusted-software-foundry/tsc/spec"
{{ range .Components }}	{{ cleanAlias .Name }} "{{ .Module }}"
{{ end }})

func main{{ pascal .Service.Name }}() {
	resources := []spec.ResourceDefinition{}
	app := spec.NewApplication(resources)
{{ range .Components }}	app.AddComponent({{ cleanAlias .Name }}.New())
{{ end }}
	configs := map[string]spec.ComponentConfig{}
	if err := app.Configure(configs); err != nil {
		fmt.Fprintf(os.Stderr, "configure: %v\n", err)
		os.Exit(1)
	}
	if err := app.Register(); err != nil {
		fmt.Fprintf(os.Stderr, "register: %v\n", err)
		os.Exit(1)
	}

	ctx, cancel := signal.NotifyContext(context.Background(), syscall.SIGINT, syscall.SIGTERM)
	defer cancel()

	if err := app.Run(ctx); err != nil {
		fmt.Fprintf(os.Stderr, "run: %v\n", err)
		os.Exit(1)
	}
}
`))

type serviceMainData struct {
	IR         *spec.IRSpec
	Service    spec.IRService
	Components []ResolvedComponent
}

func (g *Generator) writeServiceMains(ir *spec.IRSpec, components []ResolvedComponent) error {
	if len(ir.Services) == 0 {
		return nil
	}

	// Build component lookup by name for filtering per-service components.
	compByName := map[string]ResolvedComponent{}
	for _, c := range components {
		compByName[c.Name] = c
	}

	for _, svc := range ir.Services {
		// Select components for this service (subset or all).
		var svcComponents []ResolvedComponent
		if len(svc.Components) == 0 {
			svcComponents = components
		} else {
			for _, name := range svc.Components {
				if c, ok := compByName[name]; ok {
					svcComponents = append(svcComponents, c)
				}
			}
		}
		svcComponents = sortComponents(svcComponents)

		data := serviceMainData{
			IR:         ir,
			Service:    svc,
			Components: svcComponents,
		}

		var buf bytes.Buffer
		if err := serviceMainTemplate.Execute(&buf, data); err != nil {
			return fmt.Errorf("rendering main_%s.go: %w", svc.Name, err)
		}
		formatted, err := format.Source(buf.Bytes())
		if err != nil {
			return fmt.Errorf("formatting main_%s.go: %w\nsource:\n%s", svc.Name, err, buf.String())
		}
		filename := "main_" + toSnakeCase(svc.Name) + ".go"
		if err := os.WriteFile(filepath.Join(g.outputDir, filename), formatted, 0644); err != nil {
			return fmt.Errorf("writing %s: %w", filename, err)
		}
	}
	return nil
}

var dockerComposeTemplate = template.Must(template.New("compose").Parse(`# Code generated by forge compile. DO NOT EDIT.
# Spec: {{ .IR.Metadata.Name }} v{{ .IR.Metadata.Version }}
version: "3.9"
services:
{{ range .IR.Services }}  {{ .Name }}:
    build: .
    command: ["/app-{{ .Name }}"]
{{ if .Port }}    ports:
      - "{{ .Port }}:{{ .Port }}"
{{ end }}    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/{{ $.IR.Metadata.Name }}
    depends_on:
      - postgres

{{ end }}  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: {{ .IR.Metadata.Name }}
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
`))

type dockerComposeData struct {
	IR *spec.IRSpec
}

func (g *Generator) writeDockerCompose(ir *spec.IRSpec) error {
	if len(ir.Services) == 0 {
		return nil
	}
	data := dockerComposeData{IR: ir}
	var buf bytes.Buffer
	if err := dockerComposeTemplate.Execute(&buf, data); err != nil {
		return fmt.Errorf("rendering docker-compose.yaml: %w", err)
	}
	return os.WriteFile(filepath.Join(g.outputDir, "docker-compose.yaml"), buf.Bytes(), 0644)
}

// --------------------------------------------------------------------------
// Hooks codegen — generates foundry/types.go + hook_registry.go
// Implements the HOOKS_CONTRACT.md spec (frozen by TSC-Architect, PR #10).
// --------------------------------------------------------------------------

// foundryTypesTemplate generates the foundry/types.go file with HookContext and
// all request/result types used by hook function signatures.
var foundryTypesTemplate = template.Must(template.New("foundry_types").Parse(`// Code generated by forge compile. DO NOT EDIT.
// Foundry hook shared types — implementing docs/HOOKS_CONTRACT.md
package foundry

import (
	"context"
	"net/http"
	"time"
)

// HookContext is passed to every hook function. It carries operation context,
// a structured logger, and request-scoped metadata.
type HookContext struct {
	// Ctx is the request or event context. Respect cancellation.
	Ctx context.Context

	// Logger is a structured logger scoped to this operation.
	Logger Logger

	// Tracer is an OpenTelemetry tracer for creating child spans.
	Tracer Tracer

	// AppName is the application name from metadata.name.
	AppName string

	// TenantID is the resolved tenant identifier, or "" for single-tenant apps.
	TenantID string
}

// Logger is a minimal structured logging interface.
type Logger interface {
	Info(msg string, fields ...Field)
	Warn(msg string, fields ...Field)
	Error(msg string, fields ...Field)
	With(fields ...Field) Logger
}

// Field is a structured log field.
type Field struct {
	Key   string
	Value any
}

// Tracer wraps OpenTelemetry tracing.
type Tracer interface {
	Start(ctx context.Context, spanName string) (context.Context, Span)
}

// Span is an OpenTelemetry span.
type Span interface {
	End()
	SetAttribute(key string, value any)
	RecordError(err error)
}

// PostHandlerRequest carries the response details available after the handler runs.
type PostHandlerRequest struct {
	// Method and Path of the handled request.
	Method string
	Path   string

	// StatusCode is the HTTP status code that was written.
	StatusCode int

	// ResponseBytes is the number of bytes written to the response body.
	ResponseBytes int64

	// Duration is the time taken by the handler (excluding this hook).
	Duration time.Duration

	// RequestHeaders are the incoming request headers.
	RequestHeaders http.Header
}

// DBOperation describes a database operation about to execute.
type DBOperation struct {
	// Resource is the resource name, e.g. "Dinosaur".
	Resource string

	// Operation is one of: "create", "read", "update", "delete", "list".
	Operation string

	// ID is the resource primary key (empty for create and list).
	ID string

	// Payload is the mutable record payload for create/update operations.
	// Mutating Payload here will affect the values written to the database.
	Payload map[string]any

	// Filter is the query filter for list/read operations.
	Filter map[string]any
}

// DBResult carries the outcome of a completed database operation.
type DBResult struct {
	// Resource and Operation mirror the DBOperation fields.
	Resource  string
	Operation string

	// ID is the primary key of the affected record.
	ID string

	// RowsAffected is the number of rows modified (create/update/delete).
	RowsAffected int64

	// Error is the database error, if any. Non-nil errors abort the operation.
	Error error
}

// EventMessage is the message being published to the event bus.
type EventMessage struct {
	// Topic is the destination topic or subject.
	Topic string

	// Key is the optional partition/routing key.
	Key string

	// Payload is the mutable message body. Mutations affect what is published.
	Payload []byte

	// Headers are message-level metadata.
	Headers map[string]string
}

// ConsumedEvent is the event received from the event bus.
type ConsumedEvent struct {
	// Topic is the source topic or subject.
	Topic string

	// Key is the message partition key.
	Key string

	// Payload is the raw message body.
	Payload []byte

	// Headers are message-level metadata.
	Headers map[string]string

	// Offset is the message position (Kafka) or sequence (NATS).
	Offset int64
}
`))

func (g *Generator) writeFoundryTypes(ir *spec.IRSpec) error {
	if len(ir.Hooks) == 0 {
		return nil
	}
	foundryDir := filepath.Join(g.outputDir, "foundry")
	if err := os.MkdirAll(foundryDir, 0755); err != nil {
		return fmt.Errorf("creating foundry/ dir: %w", err)
	}
	var buf bytes.Buffer
	if err := foundryTypesTemplate.Execute(&buf, nil); err != nil {
		return fmt.Errorf("rendering foundry/types.go: %w", err)
	}
	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return fmt.Errorf("formatting foundry/types.go: %w", err)
	}
	return os.WriteFile(filepath.Join(foundryDir, "types.go"), formatted, 0644)
}

// hookRegistryTemplate generates the call site dispatch code in hook_registry.go.
// Each hook entry produces a typed call site matching the HOOKS_CONTRACT.md signatures.
var hookRegistryTemplate = template.Must(template.New("hook_registry").Funcs(template.FuncMap{
	"funcName": hookFuncName,
	"callSite": hookCallSite,
}).Parse(`// Code generated by forge compile. DO NOT EDIT.
// Hook registry — call sites for: {{ .IR.Metadata.Name }} v{{ .IR.Metadata.Version }}
// Human hook implementations are in hooks/*.go — never edit call sites.
// Implements docs/HOOKS_CONTRACT.md (frozen by TSC-Architect).
package main

import (
	"net/http"

	"github.com/jsell-rh/trusted-software-foundry/foundry"
	"{{ .AppModule }}/hooks"
)

{{ range .Hooks }}// {{ funcName . }} is the generated call site for hook "{{ .Name }}" at point {{ .Point }}.
// Implementation file: {{ .Implementation }}
func {{ funcName . }}({{ callSite . "sig" }}) error {
	return hooks.{{ funcName . }}({{ callSite . "call" }})
}

{{ end }}
`))

// hookFuncName returns the PascalCase function name for a hook.
// Hook name "audit-log" + point "pre-handler" → "AuditLogPreHandler"
func hookFuncName(h spec.IRHook) string {
	name := toPascalCase(h.Name)
	point := toPascalCase(h.Point)
	return name + point
}

// hookCallSite returns the parameter signature or argument list for a hook call site.
// mode "sig" = parameter declarations; mode "call" = argument list.
func hookCallSite(h spec.IRHook, mode string) string {
	switch h.Point {
	case "pre-handler":
		if mode == "sig" {
			return "hctx *foundry.HookContext, w http.ResponseWriter, r *http.Request"
		}
		return "hctx, w, r"
	case "post-handler":
		if mode == "sig" {
			return "hctx *foundry.HookContext, req *foundry.PostHandlerRequest"
		}
		return "hctx, req"
	case "pre-db":
		if mode == "sig" {
			return "hctx *foundry.HookContext, op *foundry.DBOperation"
		}
		return "hctx, op"
	case "post-db":
		if mode == "sig" {
			return "hctx *foundry.HookContext, result *foundry.DBResult"
		}
		return "hctx, result"
	case "pre-publish":
		if mode == "sig" {
			return "hctx *foundry.HookContext, msg *foundry.EventMessage"
		}
		return "hctx, msg"
	case "post-consume":
		if mode == "sig" {
			return "hctx *foundry.HookContext, event *foundry.ConsumedEvent"
		}
		return "hctx, event"
	default:
		if mode == "sig" {
			return "hctx *foundry.HookContext"
		}
		return "hctx"
	}
}

type hookRegistryData struct {
	IR        *spec.IRSpec
	Hooks     []spec.IRHook
	AppModule string
}

func (g *Generator) writeHookRegistry(ir *spec.IRSpec, appModule string) error {
	if len(ir.Hooks) == 0 {
		return nil
	}
	data := hookRegistryData{
		IR:        ir,
		Hooks:     ir.Hooks,
		AppModule: appModule,
	}
	var buf bytes.Buffer
	if err := hookRegistryTemplate.Execute(&buf, data); err != nil {
		return fmt.Errorf("rendering hook_registry.go: %w", err)
	}
	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return fmt.Errorf("formatting hook_registry.go: %w\nsource:\n%s", err, buf.String())
	}
	return os.WriteFile(filepath.Join(g.outputDir, "hook_registry.go"), formatted, 0644)
}

// copyHookFiles copies all declared hooks/*.go source files into the generated project.
// Hook files are human-written and must be copied unchanged — the compiler never modifies them.
// If a hook file does not yet exist on disk, it is skipped gracefully (engineers write it later).
func copyHookFiles(ir *spec.IRSpec, outputDir string) error {
	if len(ir.Hooks) == 0 {
		return nil
	}
	for _, h := range ir.Hooks {
		if h.Implementation == "" {
			continue
		}
		data, err := os.ReadFile(h.Implementation)
		if err != nil {
			// Hook file not yet written by engineers — skip gracefully.
			continue
		}
		dest := filepath.Join(outputDir, h.Implementation)
		if err := os.MkdirAll(filepath.Dir(dest), 0755); err != nil {
			return fmt.Errorf("creating dir for %s: %w", h.Implementation, err)
		}
		if err := os.WriteFile(dest, data, 0644); err != nil {
			return fmt.Errorf("copying %s: %w", h.Implementation, err)
		}
	}
	return nil
}
