package main

import (
	"fmt"
	"os"
	"os/exec"
	"os/signal"
	"path/filepath"
	"strings"
	"syscall"

	"github.com/spf13/cobra"

	"github.com/jsell-rh/trusted-software-foundry/foundry/compiler"
	"github.com/jsell-rh/trusted-software-foundry/foundry/spec"
)

func runCmd() *cobra.Command {
	var (
		outputDir    string
		foundryPath  string
		buildOnly    bool
		noDockerBuild bool
	)

	cmd := &cobra.Command{
		Use:   "run <spec.yaml>",
		Short: "Launch the local development stack for a Foundry spec",
		Long: `forge run compiles the spec and starts all required infrastructure
(PostgreSQL, Kafka, NATS, etc.) using docker compose.

Steps performed:
  1. Compile spec → generate Go project in --output directory
  2. Write docker-compose.dev.yaml with infrastructure services
  3. Run 'docker compose -f docker-compose.dev.yaml up' (unless --build-only)

The generated Go application is NOT containerised — run it directly with:
  cd <output> && go run .

Stop the infrastructure with Ctrl+C or:
  docker compose -f <output>/docker-compose.dev.yaml down

Examples:
  forge run app.foundry.yaml
  forge run app.foundry.yaml --output ./local --build-only`,
		Args: cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			specPath := args[0]

			if outputDir == "" {
				ir, err := compiler.Parse(specPath)
				if err != nil {
					return fmt.Errorf("parse: %w", err)
				}
				outputDir = filepath.Join(os.TempDir(), "forge-run-"+ir.Metadata.Name)
			}

			// Step 1: Compile spec → Go project.
			fmt.Fprintf(cmd.OutOrStdout(), "Compiling %s → %s\n", specPath, outputDir)
			c := compiler.New(compiler.NewStubRegistry(), "", foundryPath)
			if err := c.Compile(specPath, outputDir); err != nil {
				return fmt.Errorf("compile: %w", err)
			}

			// Step 2: Generate docker-compose.dev.yaml (infrastructure only, no app container).
			ir, err := compiler.Parse(specPath)
			if err != nil {
				return fmt.Errorf("re-parse for dev compose: %w", err)
			}
			devComposePath := filepath.Join(outputDir, "docker-compose.dev.yaml")
			devCompose := buildDevCompose(ir)
			if err := os.WriteFile(devComposePath, []byte(devCompose), 0644); err != nil {
				return fmt.Errorf("writing docker-compose.dev.yaml: %w", err)
			}
			fmt.Fprintf(cmd.OutOrStdout(), "Generated %s\n", devComposePath)

			if buildOnly {
				fmt.Fprintf(cmd.OutOrStdout(), "\nInfrastructure ready. Start manually with:\n")
				fmt.Fprintf(cmd.OutOrStdout(), "  docker compose -f %s up\n", devComposePath)
				fmt.Fprintf(cmd.OutOrStdout(), "\nRun your application with:\n")
				fmt.Fprintf(cmd.OutOrStdout(), "  cd %s && go run .\n", outputDir)
				return nil
			}

			// Step 3: Run docker compose up.
			_ = noDockerBuild // future: --no-build skips 'docker compose build'
			return runDockerCompose(devComposePath)
		},
	}

	cmd.Flags().StringVarP(&outputDir, "output", "o", "", "Output directory for generated project (default: $TMPDIR/forge-run-<name>)")
	cmd.Flags().StringVar(&foundryPath, "foundry-path", "", "Local path to trusted-software-foundry checkout (go.mod replace directive)")
	cmd.Flags().BoolVar(&buildOnly, "build-only", false, "Generate files only; do not start docker compose")
	cmd.Flags().BoolVar(&noDockerBuild, "no-build", false, "Skip docker image build (use cached images)")

	return cmd
}

// buildDevCompose generates a docker-compose.dev.yaml with only infrastructure
// services (postgres, kafka, nats, redis, etc.) required by the spec. The
// application binary is NOT containerised; developers run it directly with
// 'go run .' pointing at this infrastructure.
func buildDevCompose(ir *spec.IRSpec) string {
	var sb strings.Builder
	sb.WriteString("# Generated by forge run — infrastructure only.\n")
	sb.WriteString("# Run your application separately: go run .\n")
	sb.WriteString("version: \"3.9\"\n")
	sb.WriteString("services:\n")

	// PostgreSQL — required when database block or resources are present.
	if ir.Database != nil || len(ir.Resources) > 0 {
		dbName := strings.ReplaceAll(ir.Metadata.Name, "-", "_")
		fmt.Fprintf(&sb, "  postgres:\n")
		fmt.Fprintf(&sb, "    image: postgres:15-alpine\n")
		fmt.Fprintf(&sb, "    environment:\n")
		fmt.Fprintf(&sb, "      POSTGRES_DB: %s\n", dbName)
		fmt.Fprintf(&sb, "      POSTGRES_USER: postgres\n")
		fmt.Fprintf(&sb, "      POSTGRES_PASSWORD: postgres\n")
		fmt.Fprintf(&sb, "    ports:\n")
		fmt.Fprintf(&sb, "      - \"5432:5432\"\n")
		fmt.Fprintf(&sb, "    healthcheck:\n")
		fmt.Fprintf(&sb, "      test: [\"CMD-SHELL\", \"pg_isready -U postgres\"]\n")
		fmt.Fprintf(&sb, "      interval: 5s\n")
		fmt.Fprintf(&sb, "      retries: 5\n")
		fmt.Fprintf(&sb, "\n")
	}

	// Kafka — required when events.backend=kafka.
	if ir.Events != nil && ir.Events.Backend == "kafka" {
		sb.WriteString("  zookeeper:\n")
		sb.WriteString("    image: confluentinc/cp-zookeeper:7.5.0\n")
		sb.WriteString("    environment:\n")
		sb.WriteString("      ZOOKEEPER_CLIENT_PORT: 2181\n")
		sb.WriteString("\n")
		sb.WriteString("  kafka:\n")
		sb.WriteString("    image: confluentinc/cp-kafka:7.5.0\n")
		sb.WriteString("    depends_on: [zookeeper]\n")
		sb.WriteString("    ports:\n")
		sb.WriteString("      - \"9092:9092\"\n")
		sb.WriteString("    environment:\n")
		sb.WriteString("      KAFKA_BROKER_ID: 1\n")
		sb.WriteString("      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181\n")
		sb.WriteString("      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092\n")
		sb.WriteString("      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1\n")
		sb.WriteString("\n")
	}

	// NATS — required when events.backend=nats.
	if ir.Events != nil && ir.Events.Backend == "nats" {
		sb.WriteString("  nats:\n")
		sb.WriteString("    image: nats:2.10-alpine\n")
		sb.WriteString("    ports:\n")
		sb.WriteString("      - \"4222:4222\"\n")
		sb.WriteString("      - \"8222:8222\"\n")
		sb.WriteString("\n")
	}

	// Redis — required when state or redis-streams events backend.
	needsRedis := ir.State != nil ||
		(ir.Events != nil && (ir.Events.Backend == "redis-streams" || ir.Events.Backend == "redis"))
	if _, hasRedis := ir.Components["foundry-redis"]; hasRedis || needsRedis {
		sb.WriteString("  redis:\n")
		sb.WriteString("    image: redis:7-alpine\n")
		sb.WriteString("    ports:\n")
		sb.WriteString("      - \"6379:6379\"\n")
		sb.WriteString("\n")
	}

	// SpiceDB — required when authz.backend=spicedb.
	if ir.Authz != nil && ir.Authz.Backend == "spicedb" {
		sb.WriteString("  spicedb:\n")
		sb.WriteString("    image: authzed/spicedb:latest\n")
		sb.WriteString("    command: serve --grpc-preshared-key dev-key\n")
		sb.WriteString("    ports:\n")
		sb.WriteString("      - \"50051:50051\"\n")
		sb.WriteString("\n")
	}

	// Print connection strings as a convenience comment.
	sb.WriteString("# Environment variables for your application:\n")
	if ir.Database != nil || len(ir.Resources) > 0 {
		dbName := strings.ReplaceAll(ir.Metadata.Name, "-", "_")
		fmt.Fprintf(&sb, "# DATABASE_URL=postgres://postgres:postgres@localhost:5432/%s\n", dbName)
	}
	if ir.Events != nil && ir.Events.Backend == "kafka" {
		sb.WriteString("# KAFKA_BROKER_URL=localhost:9092\n")
	}
	if ir.Events != nil && ir.Events.Backend == "nats" {
		sb.WriteString("# NATS_URL=nats://localhost:4222\n")
	}
	if needsRedis {
		sb.WriteString("# REDIS_URL=redis://localhost:6379\n")
	}
	if ir.Authz != nil && ir.Authz.Backend == "spicedb" {
		sb.WriteString("# SPICEDB_ENDPOINT=localhost:50051\n")
		sb.WriteString("# SPICEDB_TOKEN=dev-key\n")
	}

	return sb.String()
}

// runDockerCompose executes 'docker compose -f <composePath> up' and
// blocks until the user presses Ctrl+C (SIGINT/SIGTERM), then runs
// 'docker compose -f <composePath> down'.
func runDockerCompose(composePath string) error {
	upCmd := exec.Command("docker", "compose", "-f", composePath, "up")
	upCmd.Stdout = os.Stdout
	upCmd.Stderr = os.Stderr

	if err := upCmd.Start(); err != nil {
		return fmt.Errorf("docker compose up: %w\nIs Docker running? Install from https://docs.docker.com/get-docker/", err)
	}

	// Forward signals so Ctrl+C tears down the stack.
	sigs := make(chan os.Signal, 1)
	signal.Notify(sigs, syscall.SIGINT, syscall.SIGTERM)
	go func() {
		<-sigs
		upCmd.Process.Signal(syscall.SIGTERM) //nolint:errcheck
	}()

	if err := upCmd.Wait(); err != nil {
		// docker compose exits non-zero on Ctrl+C — that's expected.
		if upCmd.ProcessState != nil && !upCmd.ProcessState.Success() {
			// Run 'docker compose down' to clean up.
			downCmd := exec.Command("docker", "compose", "-f", composePath, "down")
			downCmd.Stdout = os.Stdout
			downCmd.Stderr = os.Stderr
			downCmd.Run() //nolint:errcheck
		}
	}

	return nil
}
